package servicebus;

// Generated 21.04.2015 10:12:53 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * ApplicationLog generated by hbm2java
 */
@Entity
@Table(name = "ApplicationLog", catalog = "ServiceBus")
public class ApplicationLog implements java.io.Serializable {

	private String primaryKey;
	private Date timestamp;
	private String category;
	private Integer eventId;
	private Integer priority;
	private String severity;
	private String title;
	private String machineName;
	private String appDomainName;
	private String processId;
	private String processName;
	private String threadName;
	private String win32threadId;
	private String message;
	private String formattedMessage;

	public ApplicationLog() {
	}

	public ApplicationLog(String primaryKey) {
		this.primaryKey = primaryKey;
	}

	public ApplicationLog(String primaryKey, String category, Integer eventId,
			Integer priority, String severity, String title,
			String machineName, String appDomainName, String processId,
			String processName, String threadName, String win32threadId,
			String message, String formattedMessage) {
		this.primaryKey = primaryKey;
		this.category = category;
		this.eventId = eventId;
		this.priority = priority;
		this.severity = severity;
		this.title = title;
		this.machineName = machineName;
		this.appDomainName = appDomainName;
		this.processId = processId;
		this.processName = processName;
		this.threadName = threadName;
		this.win32threadId = win32threadId;
		this.message = message;
		this.formattedMessage = formattedMessage;
	}

	@Id
	@Column(name = "primaryKey", unique = true, nullable = false, length = 36)
	public String getPrimaryKey() {
		return this.primaryKey;
	}

	public void setPrimaryKey(String primaryKey) {
		this.primaryKey = primaryKey;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Timestamp", length = 23)
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	@Column(name = "Category", length = 64)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "EventId")
	public Integer getEventId() {
		return this.eventId;
	}

	public void setEventId(Integer eventId) {
		this.eventId = eventId;
	}

	@Column(name = "Priority")
	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	@Column(name = "Severity", length = 32)
	public String getSeverity() {
		return this.severity;
	}

	public void setSeverity(String severity) {
		this.severity = severity;
	}

	@Column(name = "Title", length = 256)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "MachineName", length = 32)
	public String getMachineName() {
		return this.machineName;
	}

	public void setMachineName(String machineName) {
		this.machineName = machineName;
	}

	@Column(name = "AppDomainName", length = 512)
	public String getAppDomainName() {
		return this.appDomainName;
	}

	public void setAppDomainName(String appDomainName) {
		this.appDomainName = appDomainName;
	}

	@Column(name = "ProcessId", length = 256)
	public String getProcessId() {
		return this.processId;
	}

	public void setProcessId(String processId) {
		this.processId = processId;
	}

	@Column(name = "ProcessName", length = 512)
	public String getProcessName() {
		return this.processName;
	}

	public void setProcessName(String processName) {
		this.processName = processName;
	}

	@Column(name = "ThreadName", length = 512)
	public String getThreadName() {
		return this.threadName;
	}

	public void setThreadName(String threadName) {
		this.threadName = threadName;
	}

	@Column(name = "Win32ThreadId", length = 128)
	public String getWin32threadId() {
		return this.win32threadId;
	}

	public void setWin32threadId(String win32threadId) {
		this.win32threadId = win32threadId;
	}

	@Column(name = "Message")
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Column(name = "FormattedMessage")
	public String getFormattedMessage() {
		return this.formattedMessage;
	}

	public void setFormattedMessage(String formattedMessage) {
		this.formattedMessage = formattedMessage;
	}

}
