package servicebus;
// Generated 21.04.2015 10:12:53 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LogMsg generated by hbm2java
 */
@Entity
@Table(name="LogMsg"
    ,catalog="ServiceBus"
)
public class LogMsg  implements java.io.Serializable {


     private String primaryKey;
     private Сообщение сообщение;

    public LogMsg() {
    }

    public LogMsg(String primaryKey, Сообщение сообщение) {
       this.primaryKey = primaryKey;
       this.сообщение = сообщение;
    }
   
     @Id 

    
    @Column(name="primaryKey", unique=true, nullable=false, length=36)
    public String getPrimaryKey() {
        return this.primaryKey;
    }
    
    public void setPrimaryKey(String primaryKey) {
        this.primaryKey = primaryKey;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MsgId", nullable=false)
    public Сообщение getСообщение() {
        return this.сообщение;
    }
    
    public void setСообщение(Сообщение сообщение) {
        this.сообщение = сообщение;
    }




}


