package servicebus;

// Generated 21.04.2015 10:12:53 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Stormfilterdetail generated by hbm2java
 */
@Entity
@Table(name = "STORMFILTERDETAIL", catalog = "ServiceBus")
public class Stormfilterdetail implements java.io.Serializable {

	private String primaryKey;
	private Stormfiltersetting stormfiltersetting;
	private String caption;
	private String dataObjectView;
	private String connectMasterProp;
	private String ownerConnectProp;

	public Stormfilterdetail() {
	}

	public Stormfilterdetail(String primaryKey,
			Stormfiltersetting stormfiltersetting, String caption,
			String dataObjectView, String connectMasterProp) {
		this.primaryKey = primaryKey;
		this.stormfiltersetting = stormfiltersetting;
		this.caption = caption;
		this.dataObjectView = dataObjectView;
		this.connectMasterProp = connectMasterProp;
	}

	public Stormfilterdetail(String primaryKey,
			Stormfiltersetting stormfiltersetting, String caption,
			String dataObjectView, String connectMasterProp,
			String ownerConnectProp) {
		this.primaryKey = primaryKey;
		this.stormfiltersetting = stormfiltersetting;
		this.caption = caption;
		this.dataObjectView = dataObjectView;
		this.connectMasterProp = connectMasterProp;
		this.ownerConnectProp = ownerConnectProp;
	}

	@Id
	@Column(name = "primaryKey", unique = true, nullable = false, length = 36)
	public String getPrimaryKey() {
		return this.primaryKey;
	}

	public void setPrimaryKey(String primaryKey) {
		this.primaryKey = primaryKey;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FilterSetting_m0", nullable = false)
	public Stormfiltersetting getStormfiltersetting() {
		return this.stormfiltersetting;
	}

	public void setStormfiltersetting(Stormfiltersetting stormfiltersetting) {
		this.stormfiltersetting = stormfiltersetting;
	}

	@Column(name = "Caption", nullable = false)
	public String getCaption() {
		return this.caption;
	}

	public void setCaption(String caption) {
		this.caption = caption;
	}

	@Column(name = "DataObjectView", nullable = false)
	public String getDataObjectView() {
		return this.dataObjectView;
	}

	public void setDataObjectView(String dataObjectView) {
		this.dataObjectView = dataObjectView;
	}

	@Column(name = "ConnectMasterProp", nullable = false)
	public String getConnectMasterProp() {
		return this.connectMasterProp;
	}

	public void setConnectMasterProp(String connectMasterProp) {
		this.connectMasterProp = connectMasterProp;
	}

	@Column(name = "OwnerConnectProp")
	public String getOwnerConnectProp() {
		return this.ownerConnectProp;
	}

	public void setOwnerConnectProp(String ownerConnectProp) {
		this.ownerConnectProp = ownerConnectProp;
	}

}
