package servicebus;

// Generated 21.04.2015 10:12:53 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Stormfilterlookup generated by hbm2java
 */
@Entity
@Table(name = "STORMFILTERLOOKUP", catalog = "ServiceBus")
public class Stormfilterlookup implements java.io.Serializable {

	private String primaryKey;
	private Stormfiltersetting stormfiltersetting;
	private String dataObjectType;
	private String container;
	private String containerTag;
	private String fieldsToView;

	public Stormfilterlookup() {
	}

	public Stormfilterlookup(String primaryKey,
			Stormfiltersetting stormfiltersetting, String dataObjectType) {
		this.primaryKey = primaryKey;
		this.stormfiltersetting = stormfiltersetting;
		this.dataObjectType = dataObjectType;
	}

	public Stormfilterlookup(String primaryKey,
			Stormfiltersetting stormfiltersetting, String dataObjectType,
			String container, String containerTag, String fieldsToView) {
		this.primaryKey = primaryKey;
		this.stormfiltersetting = stormfiltersetting;
		this.dataObjectType = dataObjectType;
		this.container = container;
		this.containerTag = containerTag;
		this.fieldsToView = fieldsToView;
	}

	@Id
	@Column(name = "primaryKey", unique = true, nullable = false, length = 36)
	public String getPrimaryKey() {
		return this.primaryKey;
	}

	public void setPrimaryKey(String primaryKey) {
		this.primaryKey = primaryKey;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FilterSetting_m0", nullable = false)
	public Stormfiltersetting getStormfiltersetting() {
		return this.stormfiltersetting;
	}

	public void setStormfiltersetting(Stormfiltersetting stormfiltersetting) {
		this.stormfiltersetting = stormfiltersetting;
	}

	@Column(name = "DataObjectType", nullable = false)
	public String getDataObjectType() {
		return this.dataObjectType;
	}

	public void setDataObjectType(String dataObjectType) {
		this.dataObjectType = dataObjectType;
	}

	@Column(name = "Container")
	public String getContainer() {
		return this.container;
	}

	public void setContainer(String container) {
		this.container = container;
	}

	@Column(name = "ContainerTag")
	public String getContainerTag() {
		return this.containerTag;
	}

	public void setContainerTag(String containerTag) {
		this.containerTag = containerTag;
	}

	@Column(name = "FieldsToView")
	public String getFieldsToView() {
		return this.fieldsToView;
	}

	public void setFieldsToView(String fieldsToView) {
		this.fieldsToView = fieldsToView;
	}

}
