package servicebus;

// Generated 21.04.2015 10:12:53 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * StormadvLimit generated by hbm2java
 */
@Entity
@Table(name = "STORMAdvLimit", catalog = "ServiceBus")
public class StormadvLimit implements java.io.Serializable {

	private String primaryKey;
	private String user;
	private Boolean published;
	private String module;
	private String name;
	private String value;
	private Integer hotKeyData;

	public StormadvLimit() {
	}

	public StormadvLimit(String primaryKey) {
		this.primaryKey = primaryKey;
	}

	public StormadvLimit(String primaryKey, String user, Boolean published,
			String module, String name, String value, Integer hotKeyData) {
		this.primaryKey = primaryKey;
		this.user = user;
		this.published = published;
		this.module = module;
		this.name = name;
		this.value = value;
		this.hotKeyData = hotKeyData;
	}

	@Id
	@Column(name = "primaryKey", unique = true, nullable = false, length = 36)
	public String getPrimaryKey() {
		return this.primaryKey;
	}

	public void setPrimaryKey(String primaryKey) {
		this.primaryKey = primaryKey;
	}

	@Column(name = "`User`")
	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	@Column(name = "Published")
	public Boolean getPublished() {
		return this.published;
	}

	public void setPublished(Boolean published) {
		this.published = published;
	}

	@Column(name = "Module")
	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	@Column(name = "Name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "HotKeyData")
	public Integer getHotKeyData() {
		return this.hotKeyData;
	}

	public void setHotKeyData(Integer hotKeyData) {
		this.hotKeyData = hotKeyData;
	}

}
