package servicebus;

// Generated 21.04.2015 10:12:53 by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StormauObjType generated by hbm2java
 */
@Entity
@Table(name = "STORMAuObjType", catalog = "ServiceBus")
public class StormauObjType implements java.io.Serializable {

	private String primaryKey;
	private Serializable name;
	private Set<StormauEntity> stormauEntities = new HashSet<StormauEntity>(0);

	public StormauObjType() {
	}

	public StormauObjType(String primaryKey, Serializable name) {
		this.primaryKey = primaryKey;
		this.name = name;
	}

	public StormauObjType(String primaryKey, Serializable name,
			Set<StormauEntity> stormauEntities) {
		this.primaryKey = primaryKey;
		this.name = name;
		this.stormauEntities = stormauEntities;
	}

	@Id
	@Column(name = "primaryKey", unique = true, nullable = false, length = 36)
	public String getPrimaryKey() {
		return this.primaryKey;
	}

	public void setPrimaryKey(String primaryKey) {
		this.primaryKey = primaryKey;
	}

	@Column(name = "Name", nullable = false)
	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stormauObjType")
	public Set<StormauEntity> getStormauEntities() {
		return this.stormauEntities;
	}

	public void setStormauEntities(Set<StormauEntity> stormauEntities) {
		this.stormauEntities = stormauEntities;
	}

}
