package servicebus;

// Generated 21.04.2015 10:12:53 by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StormauEntity generated by hbm2java
 */
@Entity
@Table(name = "STORMAuEntity", catalog = "ServiceBus")
public class StormauEntity implements java.io.Serializable {

	private String primaryKey;
	private Stormag stormag;
	private StormauObjType stormauObjType;
	private Serializable objectPrimaryKey;
	private Date operationTime;
	private Serializable operationType;
	private Serializable executionResult;
	private Serializable source;
	private Serializable serializedField;
	private Set<StormauField> stormauFields = new HashSet<StormauField>(0);

	public StormauEntity() {
	}

	public StormauEntity(String primaryKey, Stormag stormag,
			StormauObjType stormauObjType, Serializable objectPrimaryKey,
			Date operationTime, Serializable operationType,
			Serializable executionResult, Serializable source) {
		this.primaryKey = primaryKey;
		this.stormag = stormag;
		this.stormauObjType = stormauObjType;
		this.objectPrimaryKey = objectPrimaryKey;
		this.operationTime = operationTime;
		this.operationType = operationType;
		this.executionResult = executionResult;
		this.source = source;
	}

	public StormauEntity(String primaryKey, Stormag stormag,
			StormauObjType stormauObjType, Serializable objectPrimaryKey,
			Date operationTime, Serializable operationType,
			Serializable executionResult, Serializable source,
			Serializable serializedField, Set<StormauField> stormauFields) {
		this.primaryKey = primaryKey;
		this.stormag = stormag;
		this.stormauObjType = stormauObjType;
		this.objectPrimaryKey = objectPrimaryKey;
		this.operationTime = operationTime;
		this.operationType = operationType;
		this.executionResult = executionResult;
		this.source = source;
		this.serializedField = serializedField;
		this.stormauFields = stormauFields;
	}

	@Id
	@Column(name = "primaryKey", unique = true, nullable = false, length = 36)
	public String getPrimaryKey() {
		return this.primaryKey;
	}

	public void setPrimaryKey(String primaryKey) {
		this.primaryKey = primaryKey;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "User_m0", nullable = false)
	public Stormag getStormag() {
		return this.stormag;
	}

	public void setStormag(Stormag stormag) {
		this.stormag = stormag;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ObjectType_m0", nullable = false)
	public StormauObjType getStormauObjType() {
		return this.stormauObjType;
	}

	public void setStormauObjType(StormauObjType stormauObjType) {
		this.stormauObjType = stormauObjType;
	}

	@Column(name = "ObjectPrimaryKey", nullable = false)
	public Serializable getObjectPrimaryKey() {
		return this.objectPrimaryKey;
	}

	public void setObjectPrimaryKey(Serializable objectPrimaryKey) {
		this.objectPrimaryKey = objectPrimaryKey;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OperationTime", nullable = false, length = 23)
	public Date getOperationTime() {
		return this.operationTime;
	}

	public void setOperationTime(Date operationTime) {
		this.operationTime = operationTime;
	}

	@Column(name = "OperationType", nullable = false)
	public Serializable getOperationType() {
		return this.operationType;
	}

	public void setOperationType(Serializable operationType) {
		this.operationType = operationType;
	}

	@Column(name = "ExecutionResult", nullable = false)
	public Serializable getExecutionResult() {
		return this.executionResult;
	}

	public void setExecutionResult(Serializable executionResult) {
		this.executionResult = executionResult;
	}

	@Column(name = "Source", nullable = false)
	public Serializable getSource() {
		return this.source;
	}

	public void setSource(Serializable source) {
		this.source = source;
	}

	@Column(name = "SerializedField")
	public Serializable getSerializedField() {
		return this.serializedField;
	}

	public void setSerializedField(Serializable serializedField) {
		this.serializedField = serializedField;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stormauEntity")
	public Set<StormauField> getStormauFields() {
		return this.stormauFields;
	}

	public void setStormauFields(Set<StormauField> stormauFields) {
		this.stormauFields = stormauFields;
	}

}
