package servicebus;

// Generated 21.04.2015 10:12:53 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Stormnetlockdata generated by hbm2java
 */
@Entity
@Table(name = "STORMNETLOCKDATA", catalog = "ServiceBus")
public class Stormnetlockdata implements java.io.Serializable {

	private String lockKey;
	private String userName;
	private Date lockDate;

	public Stormnetlockdata() {
	}

	public Stormnetlockdata(String lockKey, String userName) {
		this.lockKey = lockKey;
		this.userName = userName;
	}

	public Stormnetlockdata(String lockKey, String userName, Date lockDate) {
		this.lockKey = lockKey;
		this.userName = userName;
		this.lockDate = lockDate;
	}

	@Id
	@Column(name = "LockKey", unique = true, nullable = false, length = 300)
	public String getLockKey() {
		return this.lockKey;
	}

	public void setLockKey(String lockKey) {
		this.lockKey = lockKey;
	}

	@Column(name = "UserName", nullable = false, length = 300)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LockDate", length = 23)
	public Date getLockDate() {
		return this.lockDate;
	}

	public void setLockDate(Date lockDate) {
		this.lockDate = lockDate;
	}

}
