package servicebus;

// Generated 21.04.2015 10:12:53 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Stormag generated by hbm2java
 */
@Entity
@Table(name = "STORMAG", catalog = "ServiceBus")
public class Stormag implements java.io.Serializable {

	private String primaryKey;
	private String name;
	private String login;
	private String pwd;
	private boolean isUser;
	private boolean isGroup;
	private boolean isRole;
	private String connString;
	private Boolean enabled;
	private String email;
	private Date createTime;
	private String creator;
	private Date editTime;
	private String editor;
	private Set<Stormlg> stormlgsForGroupM0 = new HashSet<Stormlg>(0);
	private Set<Stormlg> stormlgsForUserM0 = new HashSet<Stormlg>(0);
	private Set<StormauEntity> stormauEntities = new HashSet<StormauEntity>(0);

	public Stormag() {
	}

	public Stormag(String primaryKey, String name, boolean isUser,
			boolean isGroup, boolean isRole) {
		this.primaryKey = primaryKey;
		this.name = name;
		this.isUser = isUser;
		this.isGroup = isGroup;
		this.isRole = isRole;
	}

	public Stormag(String primaryKey, String name, String login, String pwd,
			boolean isUser, boolean isGroup, boolean isRole, String connString,
			Boolean enabled, String email, Date createTime, String creator,
			Date editTime, String editor, Set<Stormlg> stormlgsForGroupM0,
			Set<Stormlg> stormlgsForUserM0, Set<StormauEntity> stormauEntities) {
		this.primaryKey = primaryKey;
		this.name = name;
		this.login = login;
		this.pwd = pwd;
		this.isUser = isUser;
		this.isGroup = isGroup;
		this.isRole = isRole;
		this.connString = connString;
		this.enabled = enabled;
		this.email = email;
		this.createTime = createTime;
		this.creator = creator;
		this.editTime = editTime;
		this.editor = editor;
		this.stormlgsForGroupM0 = stormlgsForGroupM0;
		this.stormlgsForUserM0 = stormlgsForUserM0;
		this.stormauEntities = stormauEntities;
	}

	@Id
	@Column(name = "primaryKey", unique = true, nullable = false, length = 36)
	public String getPrimaryKey() {
		return this.primaryKey;
	}

	public void setPrimaryKey(String primaryKey) {
		this.primaryKey = primaryKey;
	}

	@Column(name = "Name", nullable = false, length = 80)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Login", length = 50)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "Pwd", length = 50)
	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	@Column(name = "IsUser", nullable = false)
	public boolean isIsUser() {
		return this.isUser;
	}

	public void setIsUser(boolean isUser) {
		this.isUser = isUser;
	}

	@Column(name = "IsGroup", nullable = false)
	public boolean isIsGroup() {
		return this.isGroup;
	}

	public void setIsGroup(boolean isGroup) {
		this.isGroup = isGroup;
	}

	@Column(name = "IsRole", nullable = false)
	public boolean isIsRole() {
		return this.isRole;
	}

	public void setIsRole(boolean isRole) {
		this.isRole = isRole;
	}

	@Column(name = "ConnString")
	public String getConnString() {
		return this.connString;
	}

	public void setConnString(String connString) {
		this.connString = connString;
	}

	@Column(name = "Enabled")
	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	@Column(name = "Email", length = 80)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateTime", length = 23)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "Creator")
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EditTime", length = 23)
	public Date getEditTime() {
		return this.editTime;
	}

	public void setEditTime(Date editTime) {
		this.editTime = editTime;
	}

	@Column(name = "Editor")
	public String getEditor() {
		return this.editor;
	}

	public void setEditor(String editor) {
		this.editor = editor;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stormagByGroupM0")
	public Set<Stormlg> getStormlgsForGroupM0() {
		return this.stormlgsForGroupM0;
	}

	public void setStormlgsForGroupM0(Set<Stormlg> stormlgsForGroupM0) {
		this.stormlgsForGroupM0 = stormlgsForGroupM0;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stormagByUserM0")
	public Set<Stormlg> getStormlgsForUserM0() {
		return this.stormlgsForUserM0;
	}

	public void setStormlgsForUserM0(Set<Stormlg> stormlgsForUserM0) {
		this.stormlgsForUserM0 = stormlgsForUserM0;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stormag")
	public Set<StormauEntity> getStormauEntities() {
		return this.stormauEntities;
	}

	public void setStormauEntities(Set<StormauEntity> stormauEntities) {
		this.stormauEntities = stormauEntities;
	}

}
