package servicebus;

// Generated 21.04.2015 10:12:53 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Stormlg generated by hbm2java
 */
@Entity
@Table(name = "STORMLG", catalog = "ServiceBus")
public class Stormlg implements java.io.Serializable {

	private String primaryKey;
	private Stormag stormagByGroupM0;
	private Stormag stormagByUserM0;
	private Date createTime;
	private String creator;
	private Date editTime;
	private String editor;

	public Stormlg() {
	}

	public Stormlg(String primaryKey, Stormag stormagByGroupM0,
			Stormag stormagByUserM0) {
		this.primaryKey = primaryKey;
		this.stormagByGroupM0 = stormagByGroupM0;
		this.stormagByUserM0 = stormagByUserM0;
	}

	public Stormlg(String primaryKey, Stormag stormagByGroupM0,
			Stormag stormagByUserM0, Date createTime, String creator,
			Date editTime, String editor) {
		this.primaryKey = primaryKey;
		this.stormagByGroupM0 = stormagByGroupM0;
		this.stormagByUserM0 = stormagByUserM0;
		this.createTime = createTime;
		this.creator = creator;
		this.editTime = editTime;
		this.editor = editor;
	}

	@Id
	@Column(name = "primaryKey", unique = true, nullable = false, length = 36)
	public String getPrimaryKey() {
		return this.primaryKey;
	}

	public void setPrimaryKey(String primaryKey) {
		this.primaryKey = primaryKey;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Group_m0", nullable = false)
	public Stormag getStormagByGroupM0() {
		return this.stormagByGroupM0;
	}

	public void setStormagByGroupM0(Stormag stormagByGroupM0) {
		this.stormagByGroupM0 = stormagByGroupM0;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "User_m0", nullable = false)
	public Stormag getStormagByUserM0() {
		return this.stormagByUserM0;
	}

	public void setStormagByUserM0(Stormag stormagByUserM0) {
		this.stormagByUserM0 = stormagByUserM0;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateTime", length = 23)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "Creator")
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EditTime", length = 23)
	public Date getEditTime() {
		return this.editTime;
	}

	public void setEditTime(Date editTime) {
		this.editTime = editTime;
	}

	@Column(name = "Editor")
	public String getEditor() {
		return this.editor;
	}

	public void setEditor(String editor) {
		this.editor = editor;
	}

}
