package servicebus;

// Generated 21.04.2015 10:12:53 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Stormfiltersetting generated by hbm2java
 */
@Entity
@Table(name = "STORMFILTERSETTING", catalog = "ServiceBus")
public class Stormfiltersetting implements java.io.Serializable {

	private String primaryKey;
	private String name;
	private String dataObjectView;
	private Set<Stormfilterlookup> stormfilterlookups = new HashSet<Stormfilterlookup>(
			0);
	private Set<Stormfilterdetail> stormfilterdetails = new HashSet<Stormfilterdetail>(
			0);
	private Set<Stormwebsearch> stormwebsearches = new HashSet<Stormwebsearch>(
			0);

	public Stormfiltersetting() {
	}

	public Stormfiltersetting(String primaryKey, String name,
			String dataObjectView) {
		this.primaryKey = primaryKey;
		this.name = name;
		this.dataObjectView = dataObjectView;
	}

	public Stormfiltersetting(String primaryKey, String name,
			String dataObjectView, Set<Stormfilterlookup> stormfilterlookups,
			Set<Stormfilterdetail> stormfilterdetails,
			Set<Stormwebsearch> stormwebsearches) {
		this.primaryKey = primaryKey;
		this.name = name;
		this.dataObjectView = dataObjectView;
		this.stormfilterlookups = stormfilterlookups;
		this.stormfilterdetails = stormfilterdetails;
		this.stormwebsearches = stormwebsearches;
	}

	@Id
	@Column(name = "primaryKey", unique = true, nullable = false, length = 36)
	public String getPrimaryKey() {
		return this.primaryKey;
	}

	public void setPrimaryKey(String primaryKey) {
		this.primaryKey = primaryKey;
	}

	@Column(name = "Name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DataObjectView", nullable = false)
	public String getDataObjectView() {
		return this.dataObjectView;
	}

	public void setDataObjectView(String dataObjectView) {
		this.dataObjectView = dataObjectView;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stormfiltersetting")
	public Set<Stormfilterlookup> getStormfilterlookups() {
		return this.stormfilterlookups;
	}

	public void setStormfilterlookups(Set<Stormfilterlookup> stormfilterlookups) {
		this.stormfilterlookups = stormfilterlookups;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stormfiltersetting")
	public Set<Stormfilterdetail> getStormfilterdetails() {
		return this.stormfilterdetails;
	}

	public void setStormfilterdetails(Set<Stormfilterdetail> stormfilterdetails) {
		this.stormfilterdetails = stormfilterdetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stormfiltersetting")
	public Set<Stormwebsearch> getStormwebsearches() {
		return this.stormwebsearches;
	}

	public void setStormwebsearches(Set<Stormwebsearch> stormwebsearches) {
		this.stormwebsearches = stormwebsearches;
	}

}
