package servicebus;

// Generated 21.04.2015 10:12:53 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserSetting generated by hbm2java
 */
@Entity
@Table(name = "UserSetting", catalog = "ServiceBus")
public class UserSetting implements java.io.Serializable {

	private String primaryKey;
	private String appName;
	private String userName;
	private String userGuid;
	private String moduleName;
	private String moduleGuid;
	private String settName;
	private String settGuid;
	private Date settLastAccessTime;
	private String strVal;
	private String txtVal;
	private Integer intVal;
	private Boolean boolVal;
	private String guidVal;
	private BigDecimal decimalVal;
	private Date dateTimeVal;

	public UserSetting() {
	}

	public UserSetting(String primaryKey) {
		this.primaryKey = primaryKey;
	}

	public UserSetting(String primaryKey, String appName, String userName,
			String userGuid, String moduleName, String moduleGuid,
			String settName, String settGuid, Date settLastAccessTime,
			String strVal, String txtVal, Integer intVal, Boolean boolVal,
			String guidVal, BigDecimal decimalVal, Date dateTimeVal) {
		this.primaryKey = primaryKey;
		this.appName = appName;
		this.userName = userName;
		this.userGuid = userGuid;
		this.moduleName = moduleName;
		this.moduleGuid = moduleGuid;
		this.settName = settName;
		this.settGuid = settGuid;
		this.settLastAccessTime = settLastAccessTime;
		this.strVal = strVal;
		this.txtVal = txtVal;
		this.intVal = intVal;
		this.boolVal = boolVal;
		this.guidVal = guidVal;
		this.decimalVal = decimalVal;
		this.dateTimeVal = dateTimeVal;
	}

	@Id
	@Column(name = "primaryKey", unique = true, nullable = false, length = 36)
	public String getPrimaryKey() {
		return this.primaryKey;
	}

	public void setPrimaryKey(String primaryKey) {
		this.primaryKey = primaryKey;
	}

	@Column(name = "AppName", length = 256)
	public String getAppName() {
		return this.appName;
	}

	public void setAppName(String appName) {
		this.appName = appName;
	}

	@Column(name = "UserName", length = 512)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "UserGuid", length = 36)
	public String getUserGuid() {
		return this.userGuid;
	}

	public void setUserGuid(String userGuid) {
		this.userGuid = userGuid;
	}

	@Column(name = "ModuleName", length = 1024)
	public String getModuleName() {
		return this.moduleName;
	}

	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}

	@Column(name = "ModuleGuid", length = 36)
	public String getModuleGuid() {
		return this.moduleGuid;
	}

	public void setModuleGuid(String moduleGuid) {
		this.moduleGuid = moduleGuid;
	}

	@Column(name = "SettName", length = 256)
	public String getSettName() {
		return this.settName;
	}

	public void setSettName(String settName) {
		this.settName = settName;
	}

	@Column(name = "SettGuid", length = 36)
	public String getSettGuid() {
		return this.settGuid;
	}

	public void setSettGuid(String settGuid) {
		this.settGuid = settGuid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SettLastAccessTime", length = 23)
	public Date getSettLastAccessTime() {
		return this.settLastAccessTime;
	}

	public void setSettLastAccessTime(Date settLastAccessTime) {
		this.settLastAccessTime = settLastAccessTime;
	}

	@Column(name = "StrVal", length = 256)
	public String getStrVal() {
		return this.strVal;
	}

	public void setStrVal(String strVal) {
		this.strVal = strVal;
	}

	@Column(name = "TxtVal")
	public String getTxtVal() {
		return this.txtVal;
	}

	public void setTxtVal(String txtVal) {
		this.txtVal = txtVal;
	}

	@Column(name = "IntVal")
	public Integer getIntVal() {
		return this.intVal;
	}

	public void setIntVal(Integer intVal) {
		this.intVal = intVal;
	}

	@Column(name = "BoolVal")
	public Boolean getBoolVal() {
		return this.boolVal;
	}

	public void setBoolVal(Boolean boolVal) {
		this.boolVal = boolVal;
	}

	@Column(name = "GuidVal", length = 36)
	public String getGuidVal() {
		return this.guidVal;
	}

	public void setGuidVal(String guidVal) {
		this.guidVal = guidVal;
	}

	@Column(name = "DecimalVal", precision = 20, scale = 10)
	public BigDecimal getDecimalVal() {
		return this.decimalVal;
	}

	public void setDecimalVal(BigDecimal decimalVal) {
		this.decimalVal = decimalVal;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateTimeVal", length = 23)
	public Date getDateTimeVal() {
		return this.dateTimeVal;
	}

	public void setDateTimeVal(Date dateTimeVal) {
		this.dateTimeVal = dateTimeVal;
	}

}
