package servicebus;
// Generated 21.04.2015 10:12:53 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Подписка generated by hbm2java
 */
@Entity
@Table(name="Подписка"
    ,catalog="ServiceBus"
)
public class Подписка  implements java.io.Serializable {


     private String primaryKey;
     private Клиент клиент;
     private ТипСообщения типСообщения;
     private Шина шина;
     private long датаПрекращения;
     private Boolean isCallBack;
     private Integer неудПопытки;
     private String передаватьПо;
     private String описание;
     private Date createTime;
     private String creator;
     private Date editTime;
     private String editor;

    public Подписка() {
    }

	
    public Подписка(String primaryKey, ТипСообщения типСообщения, long датаПрекращения) {
        this.primaryKey = primaryKey;
        this.типСообщения = типСообщения;
        this.датаПрекращения = датаПрекращения;
    }
    public Подписка(String primaryKey, Клиент клиент, ТипСообщения типСообщения, Шина шина, long датаПрекращения,
        Boolean isCallBack, Integer неудПопытки, String передаватьПо, String описание, Date createTime, String creator,
        Date editTime, String editor) {
       this.primaryKey = primaryKey;
       this.клиент = клиент;
       this.типСообщения = типСообщения;
       this.шина = шина;
       this.датаПрекращения = датаПрекращения;
       this.isCallBack = isCallBack;
       this.неудПопытки = неудПопытки;
       this.передаватьПо = передаватьПо;
       this.описание = описание;
       this.createTime = createTime;
       this.creator = creator;
       this.editTime = editTime;
       this.editor = editor;
    }
   
     @Id 

    
    @Column(name="primaryKey", unique=true, nullable=false, length=36)
    public String getPrimaryKey() {
        return this.primaryKey;
    }
    
    public void setPrimaryKey(String primaryKey) {
        this.primaryKey = primaryKey;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Клиент_m0")
    public Клиент getКлиент() {
        return this.клиент;
    }
    
    public void setКлиент(Клиент клиент) {
        this.клиент = клиент;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ТипСообщения_m0", nullable=false)
    public ТипСообщения getТипСообщения() {
        return this.типСообщения;
    }
    
    public void setТипСообщения(ТипСообщения типСообщения) {
        this.типСообщения = типСообщения;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Клиент_m1")
    public Шина getШина() {
        return this.шина;
    }
    
    public void setШина(Шина шина) {
        this.шина = шина;
    }

    
    @Column(name="ДатаПрекращения", nullable=false)
    public long getДатаПрекращения() {
        return this.датаПрекращения;
    }
    
    public void setДатаПрекращения(long датаПрекращения) {
        this.датаПрекращения = датаПрекращения;
    }

    
    @Column(name="IsCallBack")
    public Boolean getIsCallBack() {
        return this.isCallBack;
    }
    
    public void setIsCallBack(Boolean isCallBack) {
        this.isCallBack = isCallBack;
    }

    
    @Column(name="НеудПопытки")
    public Integer getНеудПопытки() {
        return this.неудПопытки;
    }
    
    public void setНеудПопытки(Integer неудПопытки) {
        this.неудПопытки = неудПопытки;
    }

    
    @Column(name="ПередаватьПо", length=4)
    public String getПередаватьПо() {
        return this.передаватьПо;
    }
    
    public void setПередаватьПо(String передаватьПо) {
        this.передаватьПо = передаватьПо;
    }

    
    @Column(name="Описание")
    public String getОписание() {
        return this.описание;
    }
    
    public void setОписание(String описание) {
        this.описание = описание;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreateTime", length=23)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    
    @Column(name="Creator")
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EditTime", length=23)
    public Date getEditTime() {
        return this.editTime;
    }
    
    public void setEditTime(Date editTime) {
        this.editTime = editTime;
    }

    
    @Column(name="Editor")
    public String getEditor() {
        return this.editor;
    }
    
    public void setEditor(String editor) {
        this.editor = editor;
    }




}


