package servicebus;
// Generated 21.04.2015 10:12:53 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Сообщение generated by hbm2java
 */
@Entity
@Table(name="Сообщение"
    ,catalog="ServiceBus"
)
public class Сообщение  implements java.io.Serializable {


     private String primaryKey;
     private Клиент клиент;
     private ТипСообщения типСообщения;
     private Шина шина;
     private String тело;
     private Date времяФормирования;
     private String отправитель;
     private String вложениеДляБазы;
     private Integer приоритет;
     private String имяГруппы;
     private Boolean отправляется;
     private Integer failsCount;
     private String тэги;
     private String logMessages;
     private Date createTime;
     private String creator;
     private Date editTime;
     private String editor;
     private Set<LogMsg> logMsgs = new HashSet<LogMsg>(0);
     private Set<Тэг> тэгs = new HashSet<Тэг>(0);

    public Сообщение() {
    }

	
    public Сообщение(String primaryKey, ТипСообщения типСообщения, Date времяФормирования) {
        this.primaryKey = primaryKey;
        this.типСообщения = типСообщения;
        this.времяФормирования = времяФормирования;
    }
    public Сообщение(String primaryKey, Клиент клиент, ТипСообщения типСообщения, Шина шина, String тело, Date времяФормирования, String отправитель, String вложениеДляБазы, Integer приоритет, String имяГруппы, Boolean отправляется, Integer failsCount, String тэги, String logMessages, Date createTime, String creator, Date editTime, String editor, Set<LogMsg> logMsgs, Set<Тэг> тэгs) {
       this.primaryKey = primaryKey;
       this.клиент = клиент;
       this.типСообщения = типСообщения;
       this.шина = шина;
       this.тело = тело;
       this.времяФормирования = времяФормирования;
       this.отправитель = отправитель;
       this.вложениеДляБазы = вложениеДляБазы;
       this.приоритет = приоритет;
       this.имяГруппы = имяГруппы;
       this.отправляется = отправляется;
       this.failsCount = failsCount;
       this.тэги = тэги;
       this.logMessages = logMessages;
       this.createTime = createTime;
       this.creator = creator;
       this.editTime = editTime;
       this.editor = editor;
       this.logMsgs = logMsgs;
       this.тэгs = тэгs;
    }
   
     @Id 

    
    @Column(name="primaryKey", unique=true, nullable=false, length=36)
    public String getPrimaryKey() {
        return this.primaryKey;
    }
    
    public void setPrimaryKey(String primaryKey) {
        this.primaryKey = primaryKey;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Получатель_m0")
    public Клиент getКлиент() {
        return this.клиент;
    }
    
    public void setКлиент(Клиент клиент) {
        this.клиент = клиент;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ТипСообщения_m0", nullable=false)
    public ТипСообщения getТипСообщения() {
        return this.типСообщения;
    }
    
    public void setТипСообщения(ТипСообщения типСообщения) {
        this.типСообщения = типСообщения;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Получатель_m1")
    public Шина getШина() {
        return this.шина;
    }
    
    public void setШина(Шина шина) {
        this.шина = шина;
    }

    
    @Column(name="Тело")
    public String getТело() {
        return this.тело;
    }
    
    public void setТело(String тело) {
        this.тело = тело;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ВремяФормирования", nullable=false, length=23)
    public Date getВремяФормирования() {
        return this.времяФормирования;
    }
    
    public void setВремяФормирования(Date времяФормирования) {
        this.времяФормирования = времяФормирования;
    }

    
    @Column(name="Отправитель")
    public String getОтправитель() {
        return this.отправитель;
    }
    
    public void setОтправитель(String отправитель) {
        this.отправитель = отправитель;
    }

    
    @Column(name="ВложениеДляБазы")
    public String getВложениеДляБазы() {
        return this.вложениеДляБазы;
    }
    
    public void setВложениеДляБазы(String вложениеДляБазы) {
        this.вложениеДляБазы = вложениеДляБазы;
    }

    
    @Column(name="Приоритет")
    public Integer getПриоритет() {
        return this.приоритет;
    }
    
    public void setПриоритет(Integer приоритет) {
        this.приоритет = приоритет;
    }

    
    @Column(name="ИмяГруппы")
    public String getИмяГруппы() {
        return this.имяГруппы;
    }
    
    public void setИмяГруппы(String имяГруппы) {
        this.имяГруппы = имяГруппы;
    }

    
    @Column(name="Отправляется")
    public Boolean getОтправляется() {
        return this.отправляется;
    }
    
    public void setОтправляется(Boolean отправляется) {
        this.отправляется = отправляется;
    }

    
    @Column(name="FailsCount")
    public Integer getFailsCount() {
        return this.failsCount;
    }
    
    public void setFailsCount(Integer failsCount) {
        this.failsCount = failsCount;
    }

    
    @Column(name="Тэги")
    public String getТэги() {
        return this.тэги;
    }
    
    public void setТэги(String тэги) {
        this.тэги = тэги;
    }

    
    @Column(name="LogMessages")
    public String getLogMessages() {
        return this.logMessages;
    }
    
    public void setLogMessages(String logMessages) {
        this.logMessages = logMessages;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreateTime", length=23)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    
    @Column(name="Creator")
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EditTime", length=23)
    public Date getEditTime() {
        return this.editTime;
    }
    
    public void setEditTime(Date editTime) {
        this.editTime = editTime;
    }

    
    @Column(name="Editor")
    public String getEditor() {
        return this.editor;
    }
    
    public void setEditor(String editor) {
        this.editor = editor;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="сообщение")
    public Set<LogMsg> getLogMsgs() {
        return this.logMsgs;
    }
    
    public void setLogMsgs(Set<LogMsg> logMsgs) {
        this.logMsgs = logMsgs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="сообщение")
    public Set<Тэг> getТэгs() {
        return this.тэгs;
    }
    
    public void setТэгs(Set<Тэг> тэгs) {
        this.тэгs = тэгs;
    }




}


