package servicebus;
// Generated 21.04.2015 10:12:53 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ТипСообщения generated by hbm2java
 */
@Entity
@Table(name="ТипСообщения"
    ,catalog="ServiceBus"
)
public class ТипСообщения  implements java.io.Serializable {


     private String primaryKey;
     private String наименование;
     private String ид;
     private String комментарий;
     private Date createTime;
     private String creator;
     private Date editTime;
     private String editor;
     private Set<Сообщение> сообщениеs = new HashSet<Сообщение>(0);
     private Set<Подписка> подпискаs = new HashSet<Подписка>(0);

    public ТипСообщения() {
    }

	
    public ТипСообщения(String primaryKey) {
        this.primaryKey = primaryKey;
    }
    public ТипСообщения(String primaryKey, String наименование, String ид, String комментарий, Date createTime,
        String creator, Date editTime, String editor, Set<Сообщение> сообщениеs, Set<Подписка> подпискаs) {
       this.primaryKey = primaryKey;
       this.наименование = наименование;
       this.ид = ид;
       this.комментарий = комментарий;
       this.createTime = createTime;
       this.creator = creator;
       this.editTime = editTime;
       this.editor = editor;
       this.сообщениеs = сообщениеs;
       this.подпискаs = подпискаs;
    }
   
     @Id 

    
    @Column(name="primaryKey", unique=true, nullable=false, length=36)
    public String getPrimaryKey() {
        return this.primaryKey;
    }
    
    public void setPrimaryKey(String primaryKey) {
        this.primaryKey = primaryKey;
    }

    
    @Column(name="Наименование", length=64)
    public String getНаименование() {
        return this.наименование;
    }
    
    public void setНаименование(String наименование) {
        this.наименование = наименование;
    }

    
    @Column(name="Ид")
    public String getИд() {
        return this.ид;
    }
    
    public void setИд(String ид) {
        this.ид = ид;
    }

    
    @Column(name="Комментарий")
    public String getКомментарий() {
        return this.комментарий;
    }
    
    public void setКомментарий(String комментарий) {
        this.комментарий = комментарий;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreateTime", length=23)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    
    @Column(name="Creator")
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EditTime", length=23)
    public Date getEditTime() {
        return this.editTime;
    }
    
    public void setEditTime(Date editTime) {
        this.editTime = editTime;
    }

    
    @Column(name="Editor")
    public String getEditor() {
        return this.editor;
    }
    
    public void setEditor(String editor) {
        this.editor = editor;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="типСообщения")
    public Set<Сообщение> getСообщениеs() {
        return this.сообщениеs;
    }
    
    public void setСообщениеs(Set<Сообщение> сообщениеs) {
        this.сообщениеs = сообщениеs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="типСообщения")
    public Set<Подписка> getПодпискаs() {
        return this.подпискаs;
    }
    
    public void setПодпискаs(Set<Подписка> подпискаs) {
        this.подпискаs = подпискаs;
    }




}


