package servicebus;
// Generated 21.04.2015 10:12:53 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Шина generated by hbm2java
 */
@Entity
@Table(name="Шина"
    ,catalog="ServiceBus"
)
public class Шина  implements java.io.Serializable {


     private String primaryKey;
     private String interopАдрес;
     private Date createTime;
     private String creator;
     private Date editTime;
     private String editor;
     private String наименование;
     private String ид;
     private String адрес;
     private String dnsIdentity;
     private Set<Подписка> подпискаs = new HashSet<Подписка>(0);
     private Set<Сообщение> сообщениеs = new HashSet<Сообщение>(0);

    public Шина() {
    }

	
    public Шина(String primaryKey) {
        this.primaryKey = primaryKey;
    }
    public Шина(String primaryKey, String interopАдрес, Date createTime, String creator, Date editTime,
        String editor, String наименование, String ид, String адрес, String dnsIdentity,
        Set<Подписка> подпискаs, Set<Сообщение> сообщениеs) {
       this.primaryKey = primaryKey;
       this.interopАдрес = interopАдрес;
       this.createTime = createTime;
       this.creator = creator;
       this.editTime = editTime;
       this.editor = editor;
       this.наименование = наименование;
       this.ид = ид;
       this.адрес = адрес;
       this.dnsIdentity = dnsIdentity;
       this.подпискаs = подпискаs;
       this.сообщениеs = сообщениеs;
    }
   
     @Id 

    
    @Column(name="primaryKey", unique=true, nullable=false, length=36)
    public String getPrimaryKey() {
        return this.primaryKey;
    }
    
    public void setPrimaryKey(String primaryKey) {
        this.primaryKey = primaryKey;
    }

    
    @Column(name="InteropАдрес")
    public String getInteropАдрес() {
        return this.interopАдрес;
    }
    
    public void setInteropАдрес(String interopАдрес) {
        this.interopАдрес = interopАдрес;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreateTime", length=23)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    
    @Column(name="Creator")
    public String getCreator() {
        return this.creator;
    }
    
    public void setCreator(String creator) {
        this.creator = creator;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EditTime", length=23)
    public Date getEditTime() {
        return this.editTime;
    }
    
    public void setEditTime(Date editTime) {
        this.editTime = editTime;
    }

    
    @Column(name="Editor")
    public String getEditor() {
        return this.editor;
    }
    
    public void setEditor(String editor) {
        this.editor = editor;
    }

    
    @Column(name="Наименование", length=64)
    public String getНаименование() {
        return this.наименование;
    }
    
    public void setНаименование(String наименование) {
        this.наименование = наименование;
    }

    
    @Column(name="Ид")
    public String getИд() {
        return this.ид;
    }
    
    public void setИд(String ид) {
        this.ид = ид;
    }

    
    @Column(name="Адрес")
    public String getАдрес() {
        return this.адрес;
    }
    
    public void setАдрес(String адрес) {
        this.адрес = адрес;
    }

    
    @Column(name="DnsIdentity")
    public String getDnsIdentity() {
        return this.dnsIdentity;
    }
    
    public void setDnsIdentity(String dnsIdentity) {
        this.dnsIdentity = dnsIdentity;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="шина")
    public Set<Подписка> getПодпискаs() {
        return this.подпискаs;
    }
    
    public void setПодпискаs(Set<Подписка> подпискаs) {
        this.подпискаs = подпискаs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="шина")
    public Set<Сообщение> getСообщениеs() {
        return this.сообщениеs;
    }
    
    public void setСообщениеs(Set<Сообщение> сообщениеs) {
        this.сообщениеs = сообщениеs;
    }




}


